{
    'name': 'ALTANMYA Stock Report Extension',
    'version': '1.0',
    'summary': 'A Dynamic report for each product, type of transaction, and transaction with retrospective effects',
    'description': "A Dynamic report that shows both beginning balance and ending balance for each product, type of transaction, and transaction with retrospective effects",
    'category': 'Inventory/Inventory',
    'author': 'ALTANMYA - TECHNOLOGY SOLUTIONS',
    'company': 'ALTANMYA - TECHNOLOGY SOLUTIONS Part of ALTANMYA GROUP',
    'website': "http://tech.altanmya.net",
    'depends': ['stock','product'],
    'data': ['security/ir.model.access.csv','security/sec.xml','views/view_actions.xml','views/view_menu.xml','views/view_pages.xml'],
    'demo': [],
    'qweb': [],
    'installable': True,
    'auto_install': False,
    'application': False,
}
